### ISSUE TITLE
Can't get AppAnalysis to work following the readme: FileNotfoundException

### ISSUE THREAD

**Issue by dsantosg11** [miwong/IntelliDroid#10]
Hi, can't get Intellidroid to work following the steps at Readme. Once I am at the folder from the code, I get the following message from the terminal at my OS X device:

```
MacBook-Pro-de-David-2:AppAnalysis dass$ ./preprocess/PreprocessAPK.sh ./Apps/App.apk 
./preprocess/IntelliDroidPreprocessAPK.sh: line 14: greadlink: command not found
mkdir: ./.dir: File exists
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
mv: ./.dir and ./.dir are identical
Input file (.//.apk) was not found or was not readable.
Unable to open './/.apk' as zip archive
Not Zip, retrying as DEX
ERROR: unable to open './/.apk': No such file or directory
./dare/retargeted/. : no such file or directory
java.io.FileNotFoundException: ./apk/classes.jar (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at sun.tools.jar.Main.run(Main.java:195)
	at sun.tools.jar.Main.main(Main.java:1288)
rm: .//dare: No such file or directory
```

Where App.apk is a compiled apk downloaded from a source which I want to analyse. I tried again converting the apk to zip, but I get the same error.

```
MacBook-Pro-de-David-2:AppAnalysis dass$ ./preprocess/PreprocessAPK.sh ./Apps/App.zip
./preprocess/IntelliDroidPreprocessAPK.sh: line 14: greadlink: command not found
mkdir: ./.dir: File exists
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
mv: ./.dir and ./.dir are identical
Input file (.//.apk) was not found or was not readable.
Unable to open './/.apk' as zip archive
Not Zip, retrying as DEX
ERROR: unable to open './/.apk': No such file or directory
./dare/retargeted/. : no such file or directory
java.io.FileNotFoundException: ./apk/classes.jar (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at sun.tools.jar.Main.run(Main.java:195)
	at sun.tools.jar.Main.main(Main.java:1288)
rm: .//dare: No such file or directory
```
Any ideas why is this happening? I checked that the dare directories exist, but don't know why the scripts is unable to read the apk or zip. I tried with different apps to check if there's a problem with that apk, but I get the same error with all of them.

Thank you for your help!

**Comment by miwong** [comment]
It seems like you're missing the greadlink command, which the preprocessing script uses.  To get it, you can use Homebrew to install the coreutils package.

**Comment by dsantosg11** [comment]
Thanks! Now it generates the bytecode, but when I try to build and run with ./IntelliDroidAppAnalysis -o /path/to/apk/folder/processed/by/previous/scripts, it says it has build correctly but it doesn't generate any files or folder. It just says that everything is up to date and:

> Use the scripts in the "preprocess" directory to extract the target APK
> prior to running analysis
> 
> BUILD SUCCESSFUL
> 
> Total time: 31.781 secs

And if I try to execute as ./IntelliDroidAppAnalysis /path/to/apk/folder/processed/by/previous/scripts/classes.jar or /IntelliDroidAppAnalysis /path/to/apk/folder/processed/by/previous/scripts/

It tells me that there are no Manifest or classes.jar, (even though they are there), and doesn't generate files anyway

> Missing AndroidManifest.xml and/or classes.jar files in target APK directory.
> 
> BUILD SUCCESSFUL
> 
> Total time: 3.807 secs

Also, when I try to execute it with the targets file, as ./IntelliDroidAppAnalysis  -t taintdroidTargets.txt ../Preprocessed_Apks/jars/apkname/ the build fails:

> Starting IntelliDroidAppAnalysis for ../../Preprocessed_Apks/jars/apkname/
> Package: packagename
> Exception in thread "main" java.lang.IllegalArgumentException: class <Extension,Ljava/lang/Object> is invalid, unexpected classloader
> 	at com.ibm.wala.ipa.cha.ClassHierarchy.addClass(ClassHierarchy.java:300)
> 	at com.ibm.wala.ipa.cha.ClassHierarchy.addAllClasses(ClassHierarchy.java:280)
> 	at com.ibm.wala.ipa.cha.ClassHierarchy.<init>(ClassHierarchy.java:241)
> 	at com.ibm.wala.ipa.cha.ClassHierarchy.<init>(ClassHierarchy.java:177)
> 	at com.ibm.wala.ipa.cha.ClassHierarchy.make(ClassHierarchy.java:1217)
> 	at com.ibm.wala.ipa.cha.ClassHierarchy.make(ClassHierarchy.java:1197)
> 	at intellidroid.appanalysis.IntelliDroidAppAnalysis.analyze(IntelliDroidAppAnalysis.java:230)
> 	at intellidroid.appanalysis.IntelliDroidAppAnalysis.main(IntelliDroidAppAnalysis.java:190)
> :run FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':run'.
> > Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> BUILD FAILED
> 
> Total time: 8.393 secs
> 

Can you tell me why this is happening and how to generate appInfo.json and constraintX_X.py files?
Thank you

Edit: It was the java version, I have solved it. Thanks anyway for the help
