### ISSUE TITLE
Missing edges in callgraph

### ISSUE THREAD

**Issue by 0-14N** [miwong/IntelliDroid#5]
Hi there,

I am using IntelliDroid to test some very simple toy examples, but seems I cannot get paths for some cases when IPC is involved. I checked the callgraph building, and found out that those key edges are missing. The following is an example:

```
Intent i = new Intent(ctx, MyService.class);
ctx.startService(i);
```

```
class MyService {
  @Override
  protected void onHandleIntent(Intent intent) {
    ...
    smsManager.sendTextMessage(...);
  }
}
```

The edge "ctx.startService --> MyService.onHandleIntent" is missing.

Also, the invocation "smsManager.sendTextMessage" didn't appear in "CallGraphInfoListener.onInvoke", which makes "sendTextMessage" not identified as a target method.

Seems the problems are all because IntelliDroid adopts the default callgraph building phase, I'm not an expert in WALA, I was wondering is there any way to customize the callgraph building? Or IntelliDroid already did this but I missed that?

Thanks!

**Comment by miwong** [comment]
IntelliDroid does customize the callgraph building process in the `AndroidAppMethodTargetSelector` class, and the edge from startService->onHandleIntent should be handled.  However, it expects that the receiver class of the onHandleIntent call be a subclass of `android.app.IntentService`.  In your example, MyService isn't a subclass of IntentService...perhaps this caused the missing edge?

Hope that helps.

**Comment by 0-14N** [comment]
Thanks for your reply. I checked the code, and found out the reason is that our "intent" is returned by another method (inter-procedural), which is not handled by IntelliDroid.
